version: '3.8'

services:
  route-back:
    build:
      context: ./backend
    container_name: backend
    network_mode: "host"
    volumes:
      - ./route.sqlite:/app/route.sqlite
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  route-front:
    build:
      context: ./front
    container_name: front
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
